"""I3 adopted_content structure validation and server-side identity rules.

The stored JSON keeps exactly what the client sent (after structural
validation); no default fields are filled in. ``group_id``/``game_id`` are
always generated by the server for new objects. On update, client-provided
IDs must already belong to this plan's current version; unknown, duplicate,
cross-plan or tampered IDs are rejected.
"""

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, ValidationError

from app import security


class ContentValidationError(Exception):
    """Structure or identity violation in adopted_content (maps to 422)."""

    code = "VALIDATION_ERROR"

    def __init__(self, message: str):
        super().__init__(message)
        self.message = message


class _ContentModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class GameModel(_ContentModel):
    game_id: str | None = None
    name: str


class MorningGroupModel(_ContentModel):
    group_id: str | None = None
    group_kind: Literal["collective", "free_choice"]
    games: list[GameModel]
    focus_guidance: str | None = None
    shared_objectives: str | None = None
    guidance_points: str | None = None


class MorningTalkModel(_ContentModel):
    topic: str | None = None
    questions: str | None = None


class GroupActivityModel(_ContentModel):
    theme: str | None = None
    objectives: str | None = None
    preparation: str | None = None
    key_points: str | None = None
    difficult_points: str | None = None
    process: str | None = None


class PostGroupGameModel(_ContentModel):
    # Required whenever this group object appears: 室内区域 / 户外 / 专用室.
    context_kind: Literal["area", "outdoor", "special_room"]
    group_id: str | None = None
    area: str | None = None
    games: list[GameModel]
    focus_guidance: str | None = None
    objectives: str | None = None
    guidance: str | None = None
    support_strategy: str | None = None


class AfternoonOutdoorModel(_ContentModel):
    group_id: str | None = None
    area: str | None = None
    games: list[GameModel]
    observation_focus: str | None = None
    objectives: str | None = None
    guidance: str | None = None
    support_strategy: str | None = None


class AdoptedContentModel(_ContentModel):
    morning_exercise_label: str | None = None
    morning_games: list[MorningGroupModel] | None = None
    morning_talk: MorningTalkModel | None = None
    group_activity: GroupActivityModel | None = None
    post_group_games: list[PostGroupGameModel] | None = None
    afternoon_outdoor: AfternoonOutdoorModel | None = None
    reflection: str | None = None


def parse_adopted_content(payload: Any) -> AdoptedContentModel:
    """Validate structure only; no ID rules and no mutation of ``payload``."""
    if not isinstance(payload, dict):
        raise ContentValidationError("adopted_content 必须是 JSON 对象")
    try:
        model = AdoptedContentModel.model_validate(payload)
    except ValidationError as exc:
        raise ContentValidationError(str(exc)) from None
    _check_morning_group_counts(model)
    return model


def _check_morning_group_counts(model: AdoptedContentModel) -> None:
    groups = model.morning_games or []
    collective = sum(1 for g in groups if g.group_kind == "collective")
    free_choice = sum(1 for g in groups if g.group_kind == "free_choice")
    if collective > 1 or free_choice > 1:
        raise ContentValidationError(
            "morning_games 最多一个 collective 组和一个 free_choice 组"
        )


def prepare_content(
    payload: Any,
    *,
    allowed_group_ids: frozenset[str] = frozenset(),
    allowed_game_ids: frozenset[str] = frozenset(),
) -> dict[str, Any]:
    """Validate structure, enforce ID rules and return the stored JSON.

    ``allowed_*_ids`` are the identities already present in the plan's
    current version (empty on create). Provided IDs must be members of that
    set; missing IDs are generated server-side; duplicates are rejected.
    """
    model = parse_adopted_content(payload)
    result: dict[str, Any] = model.model_dump(exclude_none=True)

    seen_groups: set[str] = set()
    seen_games: set[str] = set()

    for section in ("morning_games", "post_group_games"):
        for group in result.get(section) or []:
            _assign_group(
                group,
                allowed_group_ids=allowed_group_ids,
                allowed_game_ids=allowed_game_ids,
                seen_groups=seen_groups,
                seen_games=seen_games,
            )
    afternoon = result.get("afternoon_outdoor")
    if isinstance(afternoon, dict):
        _assign_group(
            afternoon,
            allowed_group_ids=allowed_group_ids,
            allowed_game_ids=allowed_game_ids,
            seen_groups=seen_groups,
            seen_games=seen_games,
        )
    return result


def _assign_group(
    group: dict[str, Any],
    *,
    allowed_group_ids: frozenset[str],
    allowed_game_ids: frozenset[str],
    seen_groups: set[str],
    seen_games: set[str],
) -> None:
    group_id = group.get("group_id")
    if group_id is None:
        group_id = _fresh_id(seen_groups | allowed_group_ids)
        group["group_id"] = group_id
    else:
        _assert_known(group_id, allowed_group_ids, "group_id")
        _assert_unique(group_id, seen_groups, "group_id")
    seen_groups.add(group_id)

    for game in group.get("games") or []:
        game_id = game.get("game_id")
        if game_id is None:
            game_id = _fresh_id(seen_games | allowed_game_ids)
            game["game_id"] = game_id
        else:
            _assert_known(game_id, allowed_game_ids, "game_id")
            _assert_unique(game_id, seen_games, "game_id")
        seen_games.add(game_id)


def _assert_known(value: str, allowed: frozenset[str], label: str) -> None:
    if value not in allowed:
        raise ContentValidationError(
            f"{value} 不是本计划已有的 {label}，拒绝未知或跨计划引用"
        )


def _assert_unique(value: str, seen: set[str], label: str) -> None:
    if value in seen:
        raise ContentValidationError(f"{label} 在同一份内容中重复：{value}")


def _fresh_id(reserved: set[str]) -> str:
    while True:
        candidate = security.generate_id()
        if candidate not in reserved:
            return candidate


def collect_identity_sets(
    adopted_content: dict[str, Any] | None,
) -> tuple[frozenset[str], frozenset[str]]:
    """Return (group_ids, game_ids) present in a stored adopted_content."""
    content = adopted_content or {}
    group_ids: set[str] = set()
    game_ids: set[str] = set()
    groups: list[dict[str, Any]] = []
    for section in ("morning_games", "post_group_games"):
        for group in content.get(section) or []:
            if isinstance(group, dict):
                groups.append(group)
    afternoon = content.get("afternoon_outdoor")
    if isinstance(afternoon, dict):
        groups.append(afternoon)
    for group in groups:
        group_id = group.get("group_id")
        if isinstance(group_id, str):
            group_ids.add(group_id)
        for game in group.get("games") or []:
            if not isinstance(game, dict):
                continue
            game_id = game.get("game_id")
            if isinstance(game_id, str):
                game_ids.add(game_id)
    return frozenset(group_ids), frozenset(game_ids)
