"""I2 base: school settings, classes, teacher assignments, preview config.

园所配置单行、真实班级、教师当前归属、配置变更预览框架，并扩展 I1 操作记录的
通用目标字段。旧操作记录映射为 account 目标；不重写历史时间、动作或版本。
"""

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision = "20260921_i2_classes_assignments"
down_revision = "20260921_i1_identity_reg"
branch_labels = None
depends_on = None


def _now() -> datetime:
    # Explicit UTC value generated by Python; never bind a SQL clause object
    # as a bulk_insert parameter.
    return datetime.now(timezone.utc).replace(tzinfo=None)


def upgrade() -> None:
    # ---- operation_records: generic target columns (I1 compatible) -------
    op.add_column(
        "operation_records",
        sa.Column("target_type", sa.String(20), nullable=True),
    )
    op.add_column(
        "operation_records",
        sa.Column(
            "target_id",
            sa.String(32, collation="utf8mb4_bin"),
            nullable=True,
        ),
    )
    op.add_column(
        "operation_records",
        sa.Column("target_version_after", sa.Integer(), nullable=True),
    )
    # Old I1 rows all targeted accounts: map them, then relax the legacy
    # account columns so non-account operations may leave them null.
    op.execute(
        "UPDATE operation_records SET target_type = 'account', "
        "target_id = target_account_id, "
        "target_version_after = account_version_after"
    )
    op.alter_column(
        "operation_records", "target_type",
        existing_type=sa.String(20), nullable=False,
    )
    op.alter_column(
        "operation_records", "target_id",
        existing_type=sa.String(32, collation="utf8mb4_bin"), nullable=False,
    )
    op.alter_column(
        "operation_records", "target_account_id",
        existing_type=sa.String(32, collation="utf8mb4_bin"), nullable=True,
    )
    op.alter_column(
        "operation_records", "account_version_after",
        existing_type=sa.Integer(), nullable=True,
    )
    op.create_check_constraint(
        "ck_operation_record_target_type",
        "operation_records",
        "target_type IN ('account', 'class', 'school', 'term', 'calendar')",
    )
    # Account-targeted rows: legacy columns remain required and consistent
    # with the generic target columns (issue 5).
    op.create_check_constraint(
        "ck_operation_record_account_target",
        "operation_records",
        "target_type <> 'account' OR ("
        "target_account_id IS NOT NULL "
        "AND account_version_after IS NOT NULL "
        "AND target_account_id = target_id "
        "AND account_version_after = target_version_after)",
    )

    # ---- school_settings singleton --------------------------------------
    op.create_table(
        "school_settings",
        sa.Column("id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("school_name", sa.String(120), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schedule_version", sa.Integer(), nullable=False),
        sa.Column("plans_started_at", sa.DateTime(timezone=False),
                  nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=False), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("id = 'singleton'",
                           name="ck_school_settings_singleton"),
        sa.CheckConstraint("version >= 1",
                           name="ck_school_settings_version"),
        sa.CheckConstraint("schedule_version >= 1",
                           name="ck_school_settings_schedule_version"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )

    # ---- classes ---------------------------------------------------------
    op.create_table(
        "classes",
        sa.Column("id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("name", sa.String(80, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("grade", sa.String(20), nullable=False),
        sa.Column("header_teacher_names", sa.JSON(), nullable=False),
        sa.Column("caregiver_name", sa.String(80), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=False), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_classes_name"),
        sa.CheckConstraint("grade IN ('small', 'middle', 'large')",
                           name="ck_classes_grade"),
        sa.CheckConstraint("version >= 1", name="ck_classes_version"),
        sa.CheckConstraint(
            "caregiver_name IS NULL OR "
            "CHAR_LENGTH(TRIM(caregiver_name)) BETWEEN 1 AND 80",
            name="ck_classes_caregiver_name",
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )

    # ---- teacher_assignments --------------------------------------------
    op.create_table(
        "teacher_assignments",
        sa.Column("teacher_id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("class_id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("assigned_by", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=False),
                  nullable=False),
        sa.PrimaryKeyConstraint("teacher_id"),
        sa.ForeignKeyConstraint(["teacher_id"], ["accounts.id"]),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"]),
        sa.ForeignKeyConstraint(["assigned_by"], ["accounts.id"]),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        "ix_teacher_assignments_class_id",
        "teacher_assignments", ["class_id"],
    )

    # ---- configuration_changes (preview framework) -----------------------
    op.create_table(
        "configuration_changes",
        sa.Column("id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("operator_id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("kind", sa.String(30), nullable=False),
        sa.Column("target_id", sa.String(32, collation="utf8mb4_bin"),
                  nullable=False),
        sa.Column("normalized_proposal", sa.JSON(), nullable=False),
        sa.Column("base_versions", sa.JSON(), nullable=False),
        sa.Column("impact_summary", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=False),
                  nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=False),
                  nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=False), nullable=True),
        sa.Column("result_reference", sa.String(255), nullable=True),
        sa.Column("result_versions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["operator_id"], ["accounts.id"]),
        sa.CheckConstraint(
            "kind IN ('school_update', 'class_create', 'class_update', "
            "'term_create', 'term_update', 'calendar_override', "
            "'calendar_reimport')",
            name="ck_configuration_changes_kind",
        ),
        sa.CheckConstraint("status IN ('pending', 'applied')",
                           name="ck_configuration_changes_status"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )

    stamp = _now()
    op.bulk_insert(
        sa.table(
            "school_settings",
            sa.column("id", sa.String(32, collation="utf8mb4_bin")),
            sa.column("school_name", sa.String(120)),
            sa.column("version", sa.Integer),
            sa.column("schedule_version", sa.Integer),
            sa.column("plans_started_at", sa.DateTime(timezone=False)),
            sa.column("created_at", sa.DateTime(timezone=False)),
            sa.column("updated_at", sa.DateTime(timezone=False)),
        ),
        [
            {
                "id": "singleton",
                "school_name": None,
                "version": 1,
                "schedule_version": 1,
                "plans_started_at": None,
                "created_at": stamp,
                "updated_at": stamp,
            },
        ],
    )


def downgrade() -> None:
    """Refuse a destructive rollback (see module docstring rationale)."""
    raise RuntimeError(
        "I2 downgrade is intentionally blocked: it would drop real "
        "classes, assignments, terms and calendar revisions. Back up and "
        "downgrade manually if truly required."
    )
